name: Go Build and Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: fleetdm/fleet
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build Linux and Windows binaries
        run: |
          GOOS=linux go build -o fleetd_tables_linux.ext ./orbit/cmd/fleetd_tables
          GOOS=windows go build -o fleetd_tables_windows.exe ./orbit/cmd/fleetd_tables 

      - name: Upload binaries to workspace
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            fleetd_tables_linux.ext
            fleetd_tables_windows.exe

  lipo-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: fleetdm/fleet
      - name: Build macOS binaries
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o fleetd_tables_amd64 ./orbit/cmd/fleetd_tables
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o fleetd_tables_arm64 ./orbit/cmd/fleetd_tables

      - name: Create universal binary for macOS
        run: |
          lipo -create fleetd_tables_amd64 fleetd_tables_arm64 -output fleetd_tables_darwin_universal.ext

      - name: Upload macOS universal binary to workspace
        uses: actions/upload-artifact@v2
        with:
          name: macos-universal
          path: fleetd_tables_darwin_universal.ext

  artifact-upload:
    runs-on: ubuntu-latest
    needs: [ build, lipo-macOS ]

    steps:
      - name: Download Windows and Linux binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: Download macOS universal binary
        uses: actions/download-artifact@v2
        with:
          name: macos-universal
      - name: Upload artifacts to release using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
          fleetd_tables_linux.ext \
          fleetd_tables_windows.exe \
          fleetd_tables_darwin_universal.ext \
          --repo edwardsb/fleet_tables
